name: first worflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: self-hosted
    name: this is the first job
    steps:
      - name: first job script
        shell: cmd
        run: echo Hello World! this is the first job!!

  secondJob:
    runs-on: ubuntu-latest
    steps:
      - name: secondJob script
      - shell: bash
        run: |
          echo this is the second job
          echo and this is a multi-line script
